helm:
  parameters:
  - name: image.repository
    value: 536285030344.dkr.ecr.ap-south-1.amazonaws.com/users
    forcestring: false
  - name: service.port
    value: "8080"
    forcestring: false
  - name: livenessProbe.httpGet.path
    value: /healthz
    forcestring: false
  - name: readinessProbe.httpGet.path
    value: /healthz
    forcestring: false
  - name: image.tag
    value: 2.5.5
    forcestring: true
  - name: image.name
    value: 536285030344.dkr.ecr.ap-south-1.amazonaws.com/users
    forcestring: true
